-- Create V2 Manuals table
create table if not exists public.v2_manuals (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    year integer,
    make text,
    model text,
    uplifted boolean default false,
    active boolean default true,
    user_id uuid references auth.users
);

-- Create V2 Sections table
create table if not exists public.v2_sections (
    id bigint generated by default as identity primary key,
    manual_id bigint references public.v2_manuals(id) on delete cascade,
    section_name text,
    first_page integer,
    length integer,
    h_level integer
);

-- Create V2 Images table
create table if not exists public.v2_images (
    id bigint generated by default as identity primary key,
    manual_id bigint references public.v2_manuals(id) on delete cascade,
    page integer,
    x integer,
    y integer,
    w integer,
    h integer
);

-- Enable RLS
alter table public.v2_manuals enable row level security;
alter table public.v2_sections enable row level security;
alter table public.v2_images enable row level security;

-- Create policies (basic ones for now, can be refined in Phase 2)
create policy "Users can view their own manuals"
    on public.v2_manuals for select
    using (auth.uid() = user_id);

create policy "Users can insert their own manuals"
    on public.v2_manuals for insert
    with check (auth.uid() = user_id);

create policy "Users can view sections of their manuals"
    on public.v2_sections for select
    using (exists (
        select 1 from public.v2_manuals
        where v2_manuals.id = v2_sections.manual_id
        and v2_manuals.user_id = auth.uid()
    ));

create policy "Users can view images of their manuals"
    on public.v2_images for select
    using (exists (
        select 1 from public.v2_manuals
        where v2_manuals.id = v2_images.manual_id
        and v2_manuals.user_id = auth.uid()
    ));
